version: "3.7"
services:
    app:
        build:
            args:
                user: juan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: currency
        container_name: currency-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - currency
            
    db:
        image: mysql:5.7
        container_name: currency-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - currency

    phpmyadmin:
        build: ./docker-compose/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - "8004:80"
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - currency

    nginx:
        image: nginx:1.17-alpine
        container_name: currency-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - currency

networks:
  currency:
    driver: bridge